POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Test after validating and lint",
    "author": "Maija Mehiläinen",
    "url": "wwww.asdlajshd.com",
    "likes": 2
}